FROM golang:alpine
# protobuf-dev protoc
RUN apk add --no-cache g++ make entr

CMD ["/bin/sh", "-c", "while true;do { find ../../internal -type f | grep -Ev '\\.(pb|twirp).go'; find $PWD -mindepth 1 -path $PWD/public -prune -o -type f -print; } | entr -r -n -d -s -- 'sleep 2;make debug';done"]
