version: "3"
services:
    frontend:
        user: $USER:$GROUP
        depends_on: []
        ports: [8081:8081]
        build:
            context: ../
            dockerfile: ./cmd/frontend/Dockerfile.dev
        working_dir: /build/cmd/frontend
        environment:
            - HOME=/build
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ../:/build/ # root of repository
    http-server:
        user: $USER:$GROUP
        depends_on: ["mongo"]
        ports: [8080:8080]
        build:
            context: ../
            dockerfile: ./cmd/http-server/Dockerfile.dev
        working_dir: /build/cmd/http-server
        environment:
            - HOME=/build
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ../cmd/frontend/dist:/build/cmd/http-server/public
            - ../:/build/ # root of repository
    worker:
        user: $USER:$GROUP
        depends_on: ["http-server", "mongo"]
        build:
            context: ../
            dockerfile: ./cmd/worker/Dockerfile.dev
        working_dir: /build/cmd/worker
        environment:
            - HOME=/build
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ../:/build/ # root of repository
    mongo:
        image: mongo:latest
        # container_name: mongo
        ports: [27017:27017]
        command: --quiet
        logging: { driver: none }
