version: "3"
volumes:
    frontend_dist: {}
    go_cache: {}
    go_path: {}
    etcd: {}
services:
    frontend:
        depends_on: []
        ports: [8081:8081]
        build:
            context: ../
            dockerfile: ./cmd/frontend/Dockerfile.dev
        working_dir: /build/cmd/frontend
        volumes:
            - frontend_dist:/build/cmd/frontend/dist
            - ../:/build/ # root of repository
    http-server:
        depends_on: ["mongo"]
        ports: [8080]
        build:
            context: ../
            dockerfile: ./cmd/http-server/Dockerfile.dev
        working_dir: /build/cmd/http-server
        volumes:
            - frontend_dist:/build/cmd/http-server/public
            - go_cache:/root/.cache/go-build
            - go_path:/go
            - ../:/build/ # root of repository
    # worker:
    #     depends_on: ["mongo"]
    #     build:
    #         context: ../
    #         dockerfile: ./cmd/worker/Dockerfile.dev
    #     working_dir: /build/cmd/worker
    #     volumes:
    #         - go_cache:/root/.cache/go-build
    #         - go_path:/go
    #         - ../:/build/ # root of repository
    mongo:
        image: mongo:latest
        ports: [27017:27017]
        command: --quiet
        logging: { driver: none }
    etcd:
        image: quay.io/coreos/etcd:v3.4.15
        ports: ["2379:2379", "2380:2380"]
        volumes:
            - etcd:/etcd-data
        command: |
            /usr/local/bin/etcd
                --name etcd
                --data-dir /etcd-data
                --initial-advertise-peer-urls http://etcd:2380
                --listen-peer-urls http://0.0.0.0:2380
                --advertise-client-urls http://etcd:2379
                --listen-client-urls http://0.0.0.0:2379
                --initial-cluster etcd=http://etcd:2380
    # nats-1:
    #     image: nats:latest
    #     ports: [4222:4222, 8222:8222, 6222]
    #     command: "--auth debug-token-here --cluster nats://0.0.0.0:6222"
    #     logging: { driver: none }
    # nats-2:
    #     image: nats:latest
    #     ports: [4223:4223]
    #     depends_on: ["nats-1"]
    #     command: "--auth debug-token-here --port 4223 --cluster nats://0.0.0.0:6222 --routes=nats://debug-token-here@nats-1:6222"
    #     logging: { driver: none }
    # nats-3:
    #     image: nats:latest
    #     ports: [4224:4224]
    #     depends_on: ["nats-1"]
    #     command: "--auth debug-token-here --port 4224 --cluster nats://0.0.0.0:6222 --routes=nats://debug-token-here@nats-1:6222"
    #     logging: { driver: none }
