version: "3"
volumes:
    frontend_cache: {}
    frontend_dist: {}
    go_cache: {}
    go_path: {}
services:
    frontend:
        depends_on: []
        ports: []
        # command: sh -c "cd /build/cmd/frontend && make debug"
        build:
            context: ../
            dockerfile: ./cmd/frontend/Dockerfile.dev
        volumes:
            - frontend_cache:/build/cmd/frontend/.cache
            - frontend_dist:/build/cmd/frontend/dist
            - ../:/build/ # root of repository
    http-server:
        depends_on: ["mongo"] # "nats-1"
        ports: [8080:8080,8081:8081]
        command: sh -c "cd /build/cmd/http-server && ./debug.sh"
        build:
            context: ../
            dockerfile: ./cmd/http-server/Dockerfile.dev
        volumes:
            - frontend_cache:/build/cmd/http-server/public/.cache
            - frontend_dist:/build/cmd/http-server/public/dist
            - go_cache:/root/.cache/go-build
            - go_path:/go
            - ../:/build/ # root of repository
    worker:
        depends_on: [] # "nats-1"
        command: sh -c "cd /build/cmd/worker && make debug"
        build:
            context: ../
            dockerfile: ./cmd/worker/Dockerfile.dev
        volumes:
            - go_cache:/root/.cache/go-build
            - go_path:/go
            - ../:/build/ # root of repository
    mongo:
        image: mongo:latest
        container_name: mongo
        ports: [27017:27017]
        command: --quiet
        logging: { driver: none }
    # nats-1:
    #     image: nats:latest
    #     ports: [4222:4222, 8222:8222, 6222]
    #     command: "--auth debug-token-here --cluster nats://0.0.0.0:6222"
    #     logging: { driver: none }
    # nats-2:
    #     image: nats:latest
    #     ports: [4223:4223]
    #     depends_on: ["nats-1"]
    #     command: "--auth debug-token-here --port 4223 --cluster nats://0.0.0.0:6222 --routes=nats://debug-token-here@nats-1:6222"
    #     logging: { driver: none }
    # nats-3:
    #     image: nats:latest
    #     ports: [4224:4224]
    #     depends_on: ["nats-1"]
    #     command: "--auth debug-token-here --port 4224 --cluster nats://0.0.0.0:6222 --routes=nats://debug-token-here@nats-1:6222"
    #     logging: { driver: none }
