version: "3"
# volumes:
#     frontend_dist: {}
#     go_cache: {}
#     go_path: {}
services:
    frontend:
        user: $USER:$GROUP
        depends_on: []
        ports: [8081:8081]
        build:
            context: ../
            dockerfile: ./cmd/frontend/Dockerfile.dev
        working_dir: /build/cmd/frontend
        environment:
            - HOME=/build
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ../.cache/frontend_dist:/build/cmd/frontend/dist
            - ../.cache/node_modules:/build/cmd/frontend/node_modules
            - ../.cache/node_dotnpm:/build/.npm
            - ../:/build/ # root of repository
    http-server:
        user: $USER:$GROUP
        depends_on: ["mongo"]
        ports: [8080:8080]
        build:
            context: ../
            dockerfile: ./cmd/http-server/Dockerfile.dev
        working_dir: /build/cmd/http-server
        environment:
            - HOME=/build
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ../.cache/frontend_dist:/build/cmd/http-server/public
            - ../.cache/go_cache:/build/.cache/go-build
            - ../.cache/go_path:/go
            - ../:/build/ # root of repository
    worker:
        user: $USER:$GROUP
        depends_on: ["http-server", "mongo"]
        build:
            context: ../
            dockerfile: ./cmd/worker/Dockerfile.dev
        working_dir: /build/cmd/worker
        environment:
            - HOME=/build
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ../.cache/go_cache:/build/.cache/go-build
            - ../.cache/go_path:/go
            - ../:/build/ # root of repository
    mongo:
        image: mongo:latest
        # container_name: mongo
        ports: [27017:27017]
        command: --quiet
        logging: { driver: none }
    # nats-1:
    #     image: nats:latest
    #     ports: [4222:4222, 8222:8222, 6222]
    #     command: "--auth debug-token-here --cluster nats://0.0.0.0:6222"
    #     logging: { driver: none }
    # nats-2:
    #     image: nats:latest
    #     ports: [4223:4223]
    #     depends_on: ["nats-1"]
    #     command: "--auth debug-token-here --port 4223 --cluster nats://0.0.0.0:6222 --routes=nats://debug-token-here@nats-1:6222"
    #     logging: { driver: none }
    # nats-3:
    #     image: nats:latest
    #     ports: [4224:4224]
    #     depends_on: ["nats-1"]
    #     command: "--auth debug-token-here --port 4224 --cluster nats://0.0.0.0:6222 --routes=nats://debug-token-here@nats-1:6222"
    #     logging: { driver: none }
