// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// DO NOT EDIT, CODE GENERATED BY entc.

package ent

import (
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrstanley/spectrograph/internal/ent/guildevent"
	"github.com/lrstanley/spectrograph/internal/ent/predicate"
)

// GuildEventDelete is the builder for deleting a GuildEvent entity.
type GuildEventDelete struct {
	config
	hooks    []Hook
	mutation *GuildEventMutation
}

// Where appends a list predicates to the GuildEventDelete builder.
func (ged *GuildEventDelete) Where(ps ...predicate.GuildEvent) *GuildEventDelete {
	ged.mutation.Where(ps...)
	return ged
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ged *GuildEventDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ged.hooks) == 0 {
		affected, err = ged.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*GuildEventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ged.mutation = mutation
			affected, err = ged.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ged.hooks) - 1; i >= 0; i-- {
			if ged.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ged.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ged.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ged *GuildEventDelete) ExecX(ctx context.Context) int {
	n, err := ged.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ged *GuildEventDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: guildevent.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: guildevent.FieldID,
			},
		},
	}
	if ps := ged.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, ged.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// GuildEventDeleteOne is the builder for deleting a single GuildEvent entity.
type GuildEventDeleteOne struct {
	ged *GuildEventDelete
}

// Exec executes the deletion query.
func (gedo *GuildEventDeleteOne) Exec(ctx context.Context) error {
	n, err := gedo.ged.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{guildevent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gedo *GuildEventDeleteOne) ExecX(ctx context.Context) {
	gedo.ged.ExecX(ctx)
}
