// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// DO NOT EDIT, CODE GENERATED BY entc.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrstanley/spectrograph/internal/ent/guildconfig"
	"github.com/lrstanley/spectrograph/internal/ent/predicate"
)

// GuildConfigDelete is the builder for deleting a GuildConfig entity.
type GuildConfigDelete struct {
	config
	hooks    []Hook
	mutation *GuildConfigMutation
}

// Where appends a list predicates to the GuildConfigDelete builder.
func (gcd *GuildConfigDelete) Where(ps ...predicate.GuildConfig) *GuildConfigDelete {
	gcd.mutation.Where(ps...)
	return gcd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (gcd *GuildConfigDelete) Exec(ctx context.Context) (int, error) {
	return withHooks[int, GuildConfigMutation](ctx, gcd.sqlExec, gcd.mutation, gcd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (gcd *GuildConfigDelete) ExecX(ctx context.Context) int {
	n, err := gcd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (gcd *GuildConfigDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(guildconfig.Table, sqlgraph.NewFieldSpec(guildconfig.FieldID, field.TypeInt))
	if ps := gcd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, gcd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	gcd.mutation.done = true
	return affected, err
}

// GuildConfigDeleteOne is the builder for deleting a single GuildConfig entity.
type GuildConfigDeleteOne struct {
	gcd *GuildConfigDelete
}

// Where appends a list predicates to the GuildConfigDelete builder.
func (gcdo *GuildConfigDeleteOne) Where(ps ...predicate.GuildConfig) *GuildConfigDeleteOne {
	gcdo.gcd.mutation.Where(ps...)
	return gcdo
}

// Exec executes the deletion query.
func (gcdo *GuildConfigDeleteOne) Exec(ctx context.Context) error {
	n, err := gcdo.gcd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{guildconfig.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (gcdo *GuildConfigDeleteOne) ExecX(ctx context.Context) {
	if err := gcdo.Exec(ctx); err != nil {
		panic(err)
	}
}
