// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// DO NOT EDIT, CODE GENERATED BY entc.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrstanley/spectrograph/internal/ent/guild"
	"github.com/lrstanley/spectrograph/internal/ent/guildadminconfig"
	"github.com/lrstanley/spectrograph/internal/ent/predicate"
)

// GuildAdminConfigQuery is the builder for querying GuildAdminConfig entities.
type GuildAdminConfigQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.GuildAdminConfig
	withGuild  *GuildQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*GuildAdminConfig) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GuildAdminConfigQuery builder.
func (gacq *GuildAdminConfigQuery) Where(ps ...predicate.GuildAdminConfig) *GuildAdminConfigQuery {
	gacq.predicates = append(gacq.predicates, ps...)
	return gacq
}

// Limit adds a limit step to the query.
func (gacq *GuildAdminConfigQuery) Limit(limit int) *GuildAdminConfigQuery {
	gacq.limit = &limit
	return gacq
}

// Offset adds an offset step to the query.
func (gacq *GuildAdminConfigQuery) Offset(offset int) *GuildAdminConfigQuery {
	gacq.offset = &offset
	return gacq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gacq *GuildAdminConfigQuery) Unique(unique bool) *GuildAdminConfigQuery {
	gacq.unique = &unique
	return gacq
}

// Order adds an order step to the query.
func (gacq *GuildAdminConfigQuery) Order(o ...OrderFunc) *GuildAdminConfigQuery {
	gacq.order = append(gacq.order, o...)
	return gacq
}

// QueryGuild chains the current query on the "guild" edge.
func (gacq *GuildAdminConfigQuery) QueryGuild() *GuildQuery {
	query := &GuildQuery{config: gacq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gacq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gacq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(guildadminconfig.Table, guildadminconfig.FieldID, selector),
			sqlgraph.To(guild.Table, guild.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, guildadminconfig.GuildTable, guildadminconfig.GuildColumn),
		)
		fromU = sqlgraph.SetNeighbors(gacq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GuildAdminConfig entity from the query.
// Returns a *NotFoundError when no GuildAdminConfig was found.
func (gacq *GuildAdminConfigQuery) First(ctx context.Context) (*GuildAdminConfig, error) {
	nodes, err := gacq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{guildadminconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) FirstX(ctx context.Context) *GuildAdminConfig {
	node, err := gacq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GuildAdminConfig ID from the query.
// Returns a *NotFoundError when no GuildAdminConfig ID was found.
func (gacq *GuildAdminConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gacq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{guildadminconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := gacq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GuildAdminConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GuildAdminConfig entity is found.
// Returns a *NotFoundError when no GuildAdminConfig entities are found.
func (gacq *GuildAdminConfigQuery) Only(ctx context.Context) (*GuildAdminConfig, error) {
	nodes, err := gacq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{guildadminconfig.Label}
	default:
		return nil, &NotSingularError{guildadminconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) OnlyX(ctx context.Context) *GuildAdminConfig {
	node, err := gacq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GuildAdminConfig ID in the query.
// Returns a *NotSingularError when more than one GuildAdminConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (gacq *GuildAdminConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gacq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{guildadminconfig.Label}
	default:
		err = &NotSingularError{guildadminconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := gacq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GuildAdminConfigs.
func (gacq *GuildAdminConfigQuery) All(ctx context.Context) ([]*GuildAdminConfig, error) {
	if err := gacq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return gacq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) AllX(ctx context.Context) []*GuildAdminConfig {
	nodes, err := gacq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GuildAdminConfig IDs.
func (gacq *GuildAdminConfigQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := gacq.Select(guildadminconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := gacq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gacq *GuildAdminConfigQuery) Count(ctx context.Context) (int, error) {
	if err := gacq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return gacq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) CountX(ctx context.Context) int {
	count, err := gacq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gacq *GuildAdminConfigQuery) Exist(ctx context.Context) (bool, error) {
	if err := gacq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return gacq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (gacq *GuildAdminConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := gacq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GuildAdminConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gacq *GuildAdminConfigQuery) Clone() *GuildAdminConfigQuery {
	if gacq == nil {
		return nil
	}
	return &GuildAdminConfigQuery{
		config:     gacq.config,
		limit:      gacq.limit,
		offset:     gacq.offset,
		order:      append([]OrderFunc{}, gacq.order...),
		predicates: append([]predicate.GuildAdminConfig{}, gacq.predicates...),
		withGuild:  gacq.withGuild.Clone(),
		// clone intermediate query.
		sql:    gacq.sql.Clone(),
		path:   gacq.path,
		unique: gacq.unique,
	}
}

// WithGuild tells the query-builder to eager-load the nodes that are connected to
// the "guild" edge. The optional arguments are used to configure the query builder of the edge.
func (gacq *GuildAdminConfigQuery) WithGuild(opts ...func(*GuildQuery)) *GuildAdminConfigQuery {
	query := &GuildQuery{config: gacq.config}
	for _, opt := range opts {
		opt(query)
	}
	gacq.withGuild = query
	return gacq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GuildAdminConfig.Query().
//		GroupBy(guildadminconfig.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gacq *GuildAdminConfigQuery) GroupBy(field string, fields ...string) *GuildAdminConfigGroupBy {
	grbuild := &GuildAdminConfigGroupBy{config: gacq.config}
	grbuild.fields = append([]string{field}, fields...)
	grbuild.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := gacq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return gacq.sqlQuery(ctx), nil
	}
	grbuild.label = guildadminconfig.Label
	grbuild.flds, grbuild.scan = &grbuild.fields, grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.GuildAdminConfig.Query().
//		Select(guildadminconfig.FieldCreateTime).
//		Scan(ctx, &v)
func (gacq *GuildAdminConfigQuery) Select(fields ...string) *GuildAdminConfigSelect {
	gacq.fields = append(gacq.fields, fields...)
	selbuild := &GuildAdminConfigSelect{GuildAdminConfigQuery: gacq}
	selbuild.label = guildadminconfig.Label
	selbuild.flds, selbuild.scan = &gacq.fields, selbuild.Scan
	return selbuild
}

func (gacq *GuildAdminConfigQuery) prepareQuery(ctx context.Context) error {
	for _, f := range gacq.fields {
		if !guildadminconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gacq.path != nil {
		prev, err := gacq.path(ctx)
		if err != nil {
			return err
		}
		gacq.sql = prev
	}
	if guildadminconfig.Policy == nil {
		return errors.New("ent: uninitialized guildadminconfig.Policy (forgotten import ent/runtime?)")
	}
	if err := guildadminconfig.Policy.EvalQuery(ctx, gacq); err != nil {
		return err
	}
	return nil
}

func (gacq *GuildAdminConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GuildAdminConfig, error) {
	var (
		nodes       = []*GuildAdminConfig{}
		withFKs     = gacq.withFKs
		_spec       = gacq.querySpec()
		loadedTypes = [1]bool{
			gacq.withGuild != nil,
		}
	)
	if gacq.withGuild != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, guildadminconfig.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GuildAdminConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GuildAdminConfig{config: gacq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(gacq.modifiers) > 0 {
		_spec.Modifiers = gacq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gacq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gacq.withGuild; query != nil {
		if err := gacq.loadGuild(ctx, query, nodes, nil,
			func(n *GuildAdminConfig, e *Guild) { n.Edges.Guild = e }); err != nil {
			return nil, err
		}
	}
	for i := range gacq.loadTotal {
		if err := gacq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gacq *GuildAdminConfigQuery) loadGuild(ctx context.Context, query *GuildQuery, nodes []*GuildAdminConfig, init func(*GuildAdminConfig), assign func(*GuildAdminConfig, *Guild)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GuildAdminConfig)
	for i := range nodes {
		if nodes[i].guild_guild_admin_config == nil {
			continue
		}
		fk := *nodes[i].guild_guild_admin_config
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	query.Where(guild.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "guild_guild_admin_config" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gacq *GuildAdminConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gacq.querySpec()
	if len(gacq.modifiers) > 0 {
		_spec.Modifiers = gacq.modifiers
	}
	_spec.Node.Columns = gacq.fields
	if len(gacq.fields) > 0 {
		_spec.Unique = gacq.unique != nil && *gacq.unique
	}
	return sqlgraph.CountNodes(ctx, gacq.driver, _spec)
}

func (gacq *GuildAdminConfigQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := gacq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (gacq *GuildAdminConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   guildadminconfig.Table,
			Columns: guildadminconfig.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: guildadminconfig.FieldID,
			},
		},
		From:   gacq.sql,
		Unique: true,
	}
	if unique := gacq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := gacq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, guildadminconfig.FieldID)
		for i := range fields {
			if fields[i] != guildadminconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gacq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gacq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gacq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gacq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gacq *GuildAdminConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gacq.driver.Dialect())
	t1 := builder.Table(guildadminconfig.Table)
	columns := gacq.fields
	if len(columns) == 0 {
		columns = guildadminconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gacq.sql != nil {
		selector = gacq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gacq.unique != nil && *gacq.unique {
		selector.Distinct()
	}
	for _, p := range gacq.predicates {
		p(selector)
	}
	for _, p := range gacq.order {
		p(selector)
	}
	if offset := gacq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gacq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GuildAdminConfigGroupBy is the group-by builder for GuildAdminConfig entities.
type GuildAdminConfigGroupBy struct {
	config
	selector
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gacgb *GuildAdminConfigGroupBy) Aggregate(fns ...AggregateFunc) *GuildAdminConfigGroupBy {
	gacgb.fns = append(gacgb.fns, fns...)
	return gacgb
}

// Scan applies the group-by query and scans the result into the given value.
func (gacgb *GuildAdminConfigGroupBy) Scan(ctx context.Context, v any) error {
	query, err := gacgb.path(ctx)
	if err != nil {
		return err
	}
	gacgb.sql = query
	return gacgb.sqlScan(ctx, v)
}

func (gacgb *GuildAdminConfigGroupBy) sqlScan(ctx context.Context, v any) error {
	for _, f := range gacgb.fields {
		if !guildadminconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := gacgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gacgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (gacgb *GuildAdminConfigGroupBy) sqlQuery() *sql.Selector {
	selector := gacgb.sql.Select()
	aggregation := make([]string, 0, len(gacgb.fns))
	for _, fn := range gacgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(gacgb.fields)+len(gacgb.fns))
		for _, f := range gacgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(gacgb.fields...)...)
}

// GuildAdminConfigSelect is the builder for selecting fields of GuildAdminConfig entities.
type GuildAdminConfigSelect struct {
	*GuildAdminConfigQuery
	selector
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (gacs *GuildAdminConfigSelect) Scan(ctx context.Context, v any) error {
	if err := gacs.prepareQuery(ctx); err != nil {
		return err
	}
	gacs.sql = gacs.GuildAdminConfigQuery.sqlQuery(ctx)
	return gacs.sqlScan(ctx, v)
}

func (gacs *GuildAdminConfigSelect) sqlScan(ctx context.Context, v any) error {
	rows := &sql.Rows{}
	query, args := gacs.sql.Query()
	if err := gacs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
