// Copyright (c) Liam Stanley <me@liamstanley.io>. All rights reserved. Use
// of this source code is governed by the MIT license that can be found in
// the LICENSE file.
//
// DO NOT EDIT, CODE GENERATED BY entc.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lrstanley/spectrograph/internal/database/ent/guild"
	"github.com/lrstanley/spectrograph/internal/database/ent/guildconfig"
	"github.com/lrstanley/spectrograph/internal/database/ent/predicate"
)

// GuildConfigQuery is the builder for querying GuildConfig entities.
type GuildConfigQuery struct {
	config
	ctx        *QueryContext
	order      []OrderFunc
	inters     []Interceptor
	predicates []predicate.GuildConfig
	withGuild  *GuildQuery
	withFKs    bool
	modifiers  []func(*sql.Selector)
	loadTotal  []func(context.Context, []*GuildConfig) error
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the GuildConfigQuery builder.
func (gcq *GuildConfigQuery) Where(ps ...predicate.GuildConfig) *GuildConfigQuery {
	gcq.predicates = append(gcq.predicates, ps...)
	return gcq
}

// Limit the number of records to be returned by this query.
func (gcq *GuildConfigQuery) Limit(limit int) *GuildConfigQuery {
	gcq.ctx.Limit = &limit
	return gcq
}

// Offset to start from.
func (gcq *GuildConfigQuery) Offset(offset int) *GuildConfigQuery {
	gcq.ctx.Offset = &offset
	return gcq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (gcq *GuildConfigQuery) Unique(unique bool) *GuildConfigQuery {
	gcq.ctx.Unique = &unique
	return gcq
}

// Order specifies how the records should be ordered.
func (gcq *GuildConfigQuery) Order(o ...OrderFunc) *GuildConfigQuery {
	gcq.order = append(gcq.order, o...)
	return gcq
}

// QueryGuild chains the current query on the "guild" edge.
func (gcq *GuildConfigQuery) QueryGuild() *GuildQuery {
	query := (&GuildClient{config: gcq.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := gcq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := gcq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(guildconfig.Table, guildconfig.FieldID, selector),
			sqlgraph.To(guild.Table, guild.FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, guildconfig.GuildTable, guildconfig.GuildColumn),
		)
		fromU = sqlgraph.SetNeighbors(gcq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first GuildConfig entity from the query.
// Returns a *NotFoundError when no GuildConfig was found.
func (gcq *GuildConfigQuery) First(ctx context.Context) (*GuildConfig, error) {
	nodes, err := gcq.Limit(1).All(setContextOp(ctx, gcq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{guildconfig.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (gcq *GuildConfigQuery) FirstX(ctx context.Context) *GuildConfig {
	node, err := gcq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first GuildConfig ID from the query.
// Returns a *NotFoundError when no GuildConfig ID was found.
func (gcq *GuildConfigQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcq.Limit(1).IDs(setContextOp(ctx, gcq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{guildconfig.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (gcq *GuildConfigQuery) FirstIDX(ctx context.Context) int {
	id, err := gcq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single GuildConfig entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one GuildConfig entity is found.
// Returns a *NotFoundError when no GuildConfig entities are found.
func (gcq *GuildConfigQuery) Only(ctx context.Context) (*GuildConfig, error) {
	nodes, err := gcq.Limit(2).All(setContextOp(ctx, gcq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{guildconfig.Label}
	default:
		return nil, &NotSingularError{guildconfig.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (gcq *GuildConfigQuery) OnlyX(ctx context.Context) *GuildConfig {
	node, err := gcq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only GuildConfig ID in the query.
// Returns a *NotSingularError when more than one GuildConfig ID is found.
// Returns a *NotFoundError when no entities are found.
func (gcq *GuildConfigQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = gcq.Limit(2).IDs(setContextOp(ctx, gcq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{guildconfig.Label}
	default:
		err = &NotSingularError{guildconfig.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (gcq *GuildConfigQuery) OnlyIDX(ctx context.Context) int {
	id, err := gcq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of GuildConfigs.
func (gcq *GuildConfigQuery) All(ctx context.Context) ([]*GuildConfig, error) {
	ctx = setContextOp(ctx, gcq.ctx, "All")
	if err := gcq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*GuildConfig, *GuildConfigQuery]()
	return withInterceptors[[]*GuildConfig](ctx, gcq, qr, gcq.inters)
}

// AllX is like All, but panics if an error occurs.
func (gcq *GuildConfigQuery) AllX(ctx context.Context) []*GuildConfig {
	nodes, err := gcq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of GuildConfig IDs.
func (gcq *GuildConfigQuery) IDs(ctx context.Context) (ids []int, err error) {
	if gcq.ctx.Unique == nil && gcq.path != nil {
		gcq.Unique(true)
	}
	ctx = setContextOp(ctx, gcq.ctx, "IDs")
	if err = gcq.Select(guildconfig.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (gcq *GuildConfigQuery) IDsX(ctx context.Context) []int {
	ids, err := gcq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (gcq *GuildConfigQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, gcq.ctx, "Count")
	if err := gcq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, gcq, querierCount[*GuildConfigQuery](), gcq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (gcq *GuildConfigQuery) CountX(ctx context.Context) int {
	count, err := gcq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (gcq *GuildConfigQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, gcq.ctx, "Exist")
	switch _, err := gcq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (gcq *GuildConfigQuery) ExistX(ctx context.Context) bool {
	exist, err := gcq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the GuildConfigQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (gcq *GuildConfigQuery) Clone() *GuildConfigQuery {
	if gcq == nil {
		return nil
	}
	return &GuildConfigQuery{
		config:     gcq.config,
		ctx:        gcq.ctx.Clone(),
		order:      append([]OrderFunc{}, gcq.order...),
		inters:     append([]Interceptor{}, gcq.inters...),
		predicates: append([]predicate.GuildConfig{}, gcq.predicates...),
		withGuild:  gcq.withGuild.Clone(),
		// clone intermediate query.
		sql:  gcq.sql.Clone(),
		path: gcq.path,
	}
}

// WithGuild tells the query-builder to eager-load the nodes that are connected to
// the "guild" edge. The optional arguments are used to configure the query builder of the edge.
func (gcq *GuildConfigQuery) WithGuild(opts ...func(*GuildQuery)) *GuildConfigQuery {
	query := (&GuildClient{config: gcq.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	gcq.withGuild = query
	return gcq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.GuildConfig.Query().
//		GroupBy(guildconfig.FieldCreateTime).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (gcq *GuildConfigQuery) GroupBy(field string, fields ...string) *GuildConfigGroupBy {
	gcq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &GuildConfigGroupBy{build: gcq}
	grbuild.flds = &gcq.ctx.Fields
	grbuild.label = guildconfig.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		CreateTime time.Time `json:"create_time,omitempty"`
//	}
//
//	client.GuildConfig.Query().
//		Select(guildconfig.FieldCreateTime).
//		Scan(ctx, &v)
func (gcq *GuildConfigQuery) Select(fields ...string) *GuildConfigSelect {
	gcq.ctx.Fields = append(gcq.ctx.Fields, fields...)
	sbuild := &GuildConfigSelect{GuildConfigQuery: gcq}
	sbuild.label = guildconfig.Label
	sbuild.flds, sbuild.scan = &gcq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a GuildConfigSelect configured with the given aggregations.
func (gcq *GuildConfigQuery) Aggregate(fns ...AggregateFunc) *GuildConfigSelect {
	return gcq.Select().Aggregate(fns...)
}

func (gcq *GuildConfigQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range gcq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, gcq); err != nil {
				return err
			}
		}
	}
	for _, f := range gcq.ctx.Fields {
		if !guildconfig.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if gcq.path != nil {
		prev, err := gcq.path(ctx)
		if err != nil {
			return err
		}
		gcq.sql = prev
	}
	if guildconfig.Policy == nil {
		return errors.New("ent: uninitialized guildconfig.Policy (forgotten import ent/runtime?)")
	}
	if err := guildconfig.Policy.EvalQuery(ctx, gcq); err != nil {
		return err
	}
	return nil
}

func (gcq *GuildConfigQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*GuildConfig, error) {
	var (
		nodes       = []*GuildConfig{}
		withFKs     = gcq.withFKs
		_spec       = gcq.querySpec()
		loadedTypes = [1]bool{
			gcq.withGuild != nil,
		}
	)
	if gcq.withGuild != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, guildconfig.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*GuildConfig).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &GuildConfig{config: gcq.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if len(gcq.modifiers) > 0 {
		_spec.Modifiers = gcq.modifiers
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, gcq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := gcq.withGuild; query != nil {
		if err := gcq.loadGuild(ctx, query, nodes, nil,
			func(n *GuildConfig, e *Guild) { n.Edges.Guild = e }); err != nil {
			return nil, err
		}
	}
	for i := range gcq.loadTotal {
		if err := gcq.loadTotal[i](ctx, nodes); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (gcq *GuildConfigQuery) loadGuild(ctx context.Context, query *GuildQuery, nodes []*GuildConfig, init func(*GuildConfig), assign func(*GuildConfig, *Guild)) error {
	ids := make([]int, 0, len(nodes))
	nodeids := make(map[int][]*GuildConfig)
	for i := range nodes {
		if nodes[i].guild_guild_config == nil {
			continue
		}
		fk := *nodes[i].guild_guild_config
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(guild.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "guild_guild_config" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (gcq *GuildConfigQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := gcq.querySpec()
	if len(gcq.modifiers) > 0 {
		_spec.Modifiers = gcq.modifiers
	}
	_spec.Node.Columns = gcq.ctx.Fields
	if len(gcq.ctx.Fields) > 0 {
		_spec.Unique = gcq.ctx.Unique != nil && *gcq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, gcq.driver, _spec)
}

func (gcq *GuildConfigQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(guildconfig.Table, guildconfig.Columns, sqlgraph.NewFieldSpec(guildconfig.FieldID, field.TypeInt))
	_spec.From = gcq.sql
	if unique := gcq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if gcq.path != nil {
		_spec.Unique = true
	}
	if fields := gcq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, guildconfig.FieldID)
		for i := range fields {
			if fields[i] != guildconfig.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := gcq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := gcq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := gcq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := gcq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (gcq *GuildConfigQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(gcq.driver.Dialect())
	t1 := builder.Table(guildconfig.Table)
	columns := gcq.ctx.Fields
	if len(columns) == 0 {
		columns = guildconfig.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if gcq.sql != nil {
		selector = gcq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if gcq.ctx.Unique != nil && *gcq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range gcq.predicates {
		p(selector)
	}
	for _, p := range gcq.order {
		p(selector)
	}
	if offset := gcq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := gcq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// GuildConfigGroupBy is the group-by builder for GuildConfig entities.
type GuildConfigGroupBy struct {
	selector
	build *GuildConfigQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (gcgb *GuildConfigGroupBy) Aggregate(fns ...AggregateFunc) *GuildConfigGroupBy {
	gcgb.fns = append(gcgb.fns, fns...)
	return gcgb
}

// Scan applies the selector query and scans the result into the given value.
func (gcgb *GuildConfigGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcgb.build.ctx, "GroupBy")
	if err := gcgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GuildConfigQuery, *GuildConfigGroupBy](ctx, gcgb.build, gcgb, gcgb.build.inters, v)
}

func (gcgb *GuildConfigGroupBy) sqlScan(ctx context.Context, root *GuildConfigQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(gcgb.fns))
	for _, fn := range gcgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*gcgb.flds)+len(gcgb.fns))
		for _, f := range *gcgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*gcgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// GuildConfigSelect is the builder for selecting fields of GuildConfig entities.
type GuildConfigSelect struct {
	*GuildConfigQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (gcs *GuildConfigSelect) Aggregate(fns ...AggregateFunc) *GuildConfigSelect {
	gcs.fns = append(gcs.fns, fns...)
	return gcs
}

// Scan applies the selector query and scans the result into the given value.
func (gcs *GuildConfigSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, gcs.ctx, "Select")
	if err := gcs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*GuildConfigQuery, *GuildConfigSelect](ctx, gcs.GuildConfigQuery, gcs, gcs.inters, v)
}

func (gcs *GuildConfigSelect) sqlScan(ctx context.Context, root *GuildConfigQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(gcs.fns))
	for _, fn := range gcs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*gcs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := gcs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
