mutation updateGuildConfig($id: ID!, $input: UpdateGuildConfigInput!) {
    updateGuildConfig(id: $id, input: $input) {
        id
    }
}

mutation updateGuildAdminConfig($id: ID!, $input: UpdateGuildAdminConfigInput!) {
    updateGuildAdminConfig(id: $id, input: $input) {
        id
    }
}

mutation banUser($id: ID!, $reason: String!) {
    banUser(id: $id, reason: $reason)
}

mutation unbanUser($id: ID!) {
    unbanUser(id: $id)
}
