mutation updateGuildConfig($id: ID!, $input: UpdateGuildConfigInput!) {
    updateGuildConfig(id: $id, input: $input) {
        id
    }
}

mutation updateGuildAdminConfig($id: ID!, $input: UpdateGuildAdminConfigInput!) {
    updateGuildAdminConfig(id: $id, input: $input) {
        id
    }
}
